/* groovylint-disable-next-line CompileStatic */
pipeline {
    // agent
    agent any

    tools {
        maven 'Maven-3.9.11'
        jdk 'JDK-8'
    }

    stages {
        stage('Fetch code') {
            steps {
                git branch: 'paac', url:'https://github.com/devopshydclub/vprofile-project.git'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn install'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
    }
}
